# Phase 1A Source Registry Review

Phase 1A builds or refreshes the AMC source registry. It does **not** download portfolio disclosure files, parse documents, or load PostgreSQL.

Source rule:

- **AMFI and SEBI** are reference/source-discovery layers.
- **AMC/provider websites** are the primary ingestion sources.

This notebook prefers existing artifacts and is non-mutating by default.

## 1. Imports and paths

In [32]:
from pathlib import Path
import json
import subprocess
import sys
from urllib.parse import urlparse

import pandas as pd
from IPython.display import Image, display


def find_repo_root():
    for candidate in (Path.cwd(), *Path.cwd().parents):
        if (candidate / 'mutual_fund_ingestion' / '__init__.py').is_file():
            return candidate
    raise RuntimeError('Run this notebook from inside the Financial Analytics Work repository.')


def available_columns(frame, requested):
    return [column for column in requested if column in frame.columns]


def show_columns(frame, requested, *, empty_message='No matching records.'):
    columns = available_columns(frame, requested)
    if frame.empty:
        print(empty_message)
        return frame.reindex(columns=columns)
    return frame.loc[:, columns]


def read_jsonl(path):
    if not path.exists():
        print(f'Missing optional artifact: {path}')
        return []
    records = []
    for line_number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
        if line.strip():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                print(f'Skipping invalid JSONL record {path}:{line_number}: {exc}')
    return records

ROOT = find_repo_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
ROOT

from mutual_fund_ingestion.registry import load_registry
from mutual_fund_ingestion.source_registry import SourceRegistryPaths, calculate_source_registry_metrics

REGISTRY_PATH = ROOT / 'configs/amc_sources.yaml'
SOURCE_PATHS = SourceRegistryPaths.from_roots(
    REGISTRY_PATH,
    ROOT / 'data/raw/mutual_funds/source_registry',
    ROOT / 'data/reports/mutual_funds',
)
PATHS = {
    'registry_config': REGISTRY_PATH,
    'candidate_history': SOURCE_PATHS.candidates,
    'latest_snapshot': SOURCE_PATHS.latest,
    'source_registry_report': SOURCE_PATHS.report_html,
}
pd.DataFrame([{'artifact': name, 'path': str(path), 'exists': path.exists()} for name, path in PATHS.items()])

,artifact,path,exists
0,registry_config,/Users/vedaangchopra/all_data/complete_technic...,True
1,candidate_history,/Users/vedaangchopra/all_data/complete_technic...,True
2,latest_snapshot,/Users/vedaangchopra/all_data/complete_technic...,True
3,source_registry_report,/Users/vedaangchopra/all_data/complete_technic...,False

## 2. Load `configs/amc_sources.yaml`

In [33]:
if REGISTRY_PATH.exists():
    registry_entries = load_registry(REGISTRY_PATH)
    registry_df = pd.DataFrame([entry.to_dict() for entry in registry_entries])
else:
    print(f'Missing required registry: {REGISTRY_PATH}')
    registry_entries = []
    registry_df = pd.DataFrame()

show_columns(registry_df, [
    'amc_name', 'source_name', 'seed_url', 'amc_website', 'enabled', 'source_role',
    'source_type', 'priority', 'expected_document_types', 'discovered_from', 'notes'
])

,amc_name,source_name,seed_url,amc_website,enabled,source_role,source_type,priority,expected_document_types,discovered_from,notes
0,360 ONE Mutual Fund,NaN,https://www.360.one/asset/mutual-funds/downloads/,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
1,Abakkus Mutual Fund,NaN,https://www.abakkusmf.com/statutory-disclosure...,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
2,Aditya Birla Sun Life Mutual Fund,NaN,https://mutualfund.adityabirlacapital.com/form...,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
3,AlphaGrep Mutual Fund,NaN,https://alphagrepmf.com/,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
4,Angel One Mutual Fund,NaN,https://www.angelonemf.com/,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
5,ASK Mutual Fund,NaN,https://www.askfinancials.com/,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
6,Axis Mutual Fund,NaN,https://www.axismf.com/statutory-disclosures,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
7,Bajaj Finserv Mutual Fund,NaN,https://www.bajajamc.com/downloads?statutory-d...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
8,Bandhan Mutual Fund,NaN,https://bandhanmutual.com/downloads/disclosures,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
9,Bank of India Mutual Fund,NaN,https://www.boimf.in/regulatory-reports,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
10,Baroda BNP Paribas Mutual Fund,NaN,https://www.barodabnpparibasmf.in/downloads/mi...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
11,Canara Robeco Mutual Fund,NaN,https://www.canararobeco.com/documents/statuto...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
12,Capitalmind Mutual Fund,NaN,https://capitalmindmf.com/statutory-disclosure...,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
13,Choice Mutual Fund,NaN,https://choicemf.com/,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
14,DSP Mutual Fund,NaN,https://www.dspim.com/mandatory-disclosures/po...,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
15,Edelweiss Mutual Fund,NaN,https://www.edelweissmf.com/statutory#Portfoli...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
16,Franklin Templeton Mutual Fund,NaN,https://www.franklintempletonindia.com/investo...,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
17,Groww Mutual Fund,NaN,https://growwmf.in/statutory-disclosure/portfolio,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
18,HDFC Mutual Fund,NaN,https://www.hdfcfund.com/statutory-disclosure/...,None,True,primary_provider,provider_disclosure_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
19,Helios Mutual Fund,NaN,https://www.heliosmf.in/portfolio-disclosure/,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
20,HSBC Mutual Fund,NaN,https://www.assetmanagement.hsbc.co.in/en/mutu...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
21,ICICI Prudential Mutual Fund,NaN,https://www.icicipruamc.com/media-center/downl...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
22,IL&FS Mutual Fund (IDF),NaN,http://www.ilfsinfrafund.com/other.php,None,True,primary_provider,provider_homepage,primary,"(statutory_disclosure,)","(manual_curated, existing_config)",Homepage fallback for IDF member; refine from ...
23,Invesco Mutual Fund,NaN,https://www.invescomutualfund.com/literature-a...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
24,ITI Mutual Fund,NaN,https://www.itiamc.com/statuory-disclosure,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
25,JioBlackRock Mutual Fund,NaN,https://www.jioblackrockamc.com/statutory-disc...,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
26,JM Financial Mutual Fund,NaN,https://www.jmfinancialmf.com/downloads/Portfo...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
27,Kotak Mahindra Mutual Fund,NaN,https://www.kotakmf.com/Information/forms-and-...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
28,LIC Mutual Fund,NaN,https://www.licmf.com/downloads/monthly-portfolio,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
29,Mahindra Manulife Mutual Fund,NaN,https://www.mahindramanulife.com/downloads#MAN...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
30,Mirae Asset Mutual Fund,NaN,https://www.miraeassetmf.co.in/downloads/portf...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
31,Motilal Oswal Mutual Fund,NaN,https://www.motilaloswalmf.com/downloads/schem...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
32,Navi Mutual Fund,NaN,https://navi.com/mutual-fund/downloads/portfolio,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
33,Nippon India Mutual Fund,NaN,https://mf.nipponindiaim.com/investor-service/...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
34,NJ Mutual Fund,NaN,https://downloads.njmutualfund.com/njmf_downlo...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
35,Old Bridge Mutual Fund,NaN,https://www.oldbridgemf.com/,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
36,PGIM India Mutual Fund,NaN,https://www.pgimindia.com/mutual-funds/disclos...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
37,PPFAS Mutual Fund,NaN,https://amc.ppfas.com/downloads/portfolio-disc...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
38,Quant Mutual Fund,NaN,https://quantmutual.com/statutory-disclosures,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
39,Quantum Mutual Fund,NaN,https://www.quantumamc.com/portfolio/combined/...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
40,Samco Mutual Fund,NaN,https://www.samcomf.com/StatutoryDisclosure,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
41,SBI Mutual Fund,NaN,https://www.sbimf.com/portfolios,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
42,Shriram Mutual Fund,NaN,https://www.shriramamc.in/investor-statutory-d...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
43,Sundaram Mutual Fund,NaN,https://www.sundarammutual.com/Monthly-Fortnig...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
44,Tata Mutual Fund,NaN,https://www.tatamutualfund.com/schemes-related,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
45,Taurus Mutual Fund,NaN,https://www.taurusmutualfund.com/downloads,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
46,The Wealth Company Mutual Fund,NaN,https://www.wealthcompanyamc.in/literature-for...,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
47,TRUST Mutual Fund,NaN,https://www.trustmf.com/disclosures?activeTab=...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
48,Unifi Mutual Fund,NaN,https://unifimf.com/statutorydocuments/#fortni...,None,True,primary_provider,provider_homepage,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",Homepage fallback; refine from profile evidence.
49,Union Mutual Fund,NaN,https://unionmf.com/about-us/downloads/fortnig...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
50,UTI Mutual Fund,NaN,https://www.utimf.com/downloads/consolidate-de...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
51,WhiteOak Capital Mutual Fund,NaN,https://mf.whiteoakamc.com/regulatory-disclosu...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
52,Zerodha Mutual Fund,NaN,https://www.zerodhafundhouse.com/resources/dis...,None,True,primary_provider,provider_download_page,primary,"(factsheet, portfolio_disclosure)","(manual_curated, existing_config)",
53,NaN,AMFI,https://www.amfiindia.com/,None,True,reference_index,industry_reference_portal,secondary,"(disclosure_index, nav_reference, scheme_metad...","(manual_reference,)","Use for source discovery and validation, not a..."
54,NaN,SEBI,https://www.sebi.gov.in/,None,True,reference_index,regulatory_reference_portal,secondary,"(disclosure_index, scheme_metadata)","(manual_reference,)",Corroborative regulatory reference; discovered...

## 3. Load Phase 1A artifacts

In [34]:
candidate_records = read_jsonl(SOURCE_PATHS.candidates)
candidate_df = pd.DataFrame(candidate_records)

if SOURCE_PATHS.latest.exists():
    latest_records = json.loads(SOURCE_PATHS.latest.read_text(encoding='utf-8'))
else:
    print(f'Missing optional artifact: {SOURCE_PATHS.latest}')
    latest_records = []
latest_df = pd.DataFrame(latest_records)

print(f'Candidate records: {len(candidate_df)}')
print(f'Latest registry records: {len(latest_df)}')
display(show_columns(candidate_df, ['amc_name', 'source_name', 'seed_url', 'source_role', 'source_type', 'discovered_from', 'confidence']))
display(show_columns(latest_df, ['amc_name', 'source_name', 'seed_url', 'source_role', 'source_type', 'discovered_from', 'unresolved_reasons']))

Candidate records: 110
Latest registry records: 55

,amc_name,source_name,seed_url,source_role,source_type,discovered_from,confidence
0,360 ONE Mutual Fund,NaN,https://www.360one.com/asset-management/mutual...,primary_provider,provider_download_page,manual_curated,unknown
1,360 ONE Mutual Fund,NaN,https://www.360one.com/asset-management/mutual...,primary_provider,provider_download_page,existing_config,unknown
2,Abakkus Mutual Fund,NaN,https://www.abakkusmf.com/statutory-disclosure...,primary_provider,provider_homepage,manual_curated,unknown
3,Abakkus Mutual Fund,NaN,https://www.abakkusmf.com/statutory-disclosure...,primary_provider,provider_homepage,existing_config,unknown
4,Aditya Birla Sun Life Mutual Fund,NaN,https://mutualfund.adityabirlacapital.com/form...,primary_provider,provider_disclosure_page,manual_curated,unknown
...,...,...,...,...,...,...,...
105,Zerodha Mutual Fund,NaN,https://www.zerodhafundhouse.com/resources/,primary_provider,provider_download_page,existing_config,unknown
106,NaN,AMFI,https://www.amfiindia.com/,reference_index,industry_reference_portal,manual_reference,high
107,NaN,SEBI,https://www.sebi.gov.in/,reference_index,regulatory_reference_portal,manual_reference,medium
108,NaN,AMFI,https://www.amfiindia.com/,reference_index,industry_reference_portal,manual_reference,high
109,NaN,SEBI,https://www.sebi.gov.in/,reference_index,regulatory_reference_portal,manual_reference,medium

,amc_name,source_name,seed_url,source_role,source_type,discovered_from,unresolved_reasons
0,360 ONE Mutual Fund,NaN,https://www.360one.com/asset-management/mutual...,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
1,Abakkus Mutual Fund,NaN,https://www.abakkusmf.com/statutory-disclosure...,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
2,Aditya Birla Sun Life Mutual Fund,NaN,https://mutualfund.adityabirlacapital.com/form...,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
3,AlphaGrep Mutual Fund,NaN,https://alphagrepmf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
4,Angel One Mutual Fund,NaN,https://www.angelonemf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
5,ASK Mutual Fund,NaN,https://www.askfinancials.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
6,Axis Mutual Fund,NaN,https://www.axismf.com/statutory-disclosures,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
7,Bajaj Finserv Mutual Fund,NaN,https://www.bajajamc.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
8,Bandhan Mutual Fund,NaN,https://bandhanmutual.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
9,Bank of India Mutual Fund,NaN,https://www.boimf.in/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
10,Baroda BNP Paribas Mutual Fund,NaN,https://www.barodabnpparibasmf.in/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
11,Canara Robeco Mutual Fund,NaN,https://www.canararobeco.com/smart-downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
12,Capitalmind Mutual Fund,NaN,https://capitalmindmf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
13,Choice Mutual Fund,NaN,https://choicemf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
14,DSP Mutual Fund,NaN,https://www.dspim.com/mandatory-disclosures,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
15,Edelweiss Mutual Fund,NaN,https://www.edelweissmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
16,Franklin Templeton Mutual Fund,NaN,https://www.franklintempletonindia.com/investo...,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
17,Groww Mutual Fund,NaN,https://www.growwmf.in/statutory-disclosures,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
18,HDFC Mutual Fund,NaN,https://www.hdfcfund.com/statutory-disclosure/...,primary_provider,provider_disclosure_page,"[manual_curated, existing_config]",[]
19,Helios Mutual Fund,NaN,https://www.heliosmf.in/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
20,HSBC Mutual Fund,NaN,https://www.assetmanagement.hsbc.co.in/en/mutu...,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
21,ICICI Prudential Mutual Fund,NaN,https://www.icicipruamc.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
22,IL&FS Mutual Fund (IDF),NaN,https://www.ilfsindia.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
23,Invesco Mutual Fund,NaN,https://invescomutualfund.com/literature-and-form,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
24,ITI Mutual Fund,NaN,https://www.itiamc.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
25,JioBlackRock Mutual Fund,NaN,https://www.jioblackrockamc.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
26,JM Financial Mutual Fund,NaN,https://www.jmfinancialmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
27,Kotak Mahindra Mutual Fund,NaN,https://www.kotakmf.com/information/forms-and-...,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
28,LIC Mutual Fund,NaN,https://www.licmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
29,Mahindra Manulife Mutual Fund,NaN,https://www.mahindramanulife.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
30,Mirae Asset Mutual Fund,NaN,https://www.miraeassetmf.co.in/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
31,Motilal Oswal Mutual Fund,NaN,https://www.motilaloswalmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
32,Navi Mutual Fund,NaN,https://navi.com/mutual-fund,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
33,Nippon India Mutual Fund,NaN,https://mf.nipponindiaim.com/InvestorServices/...,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
34,NJ Mutual Fund,NaN,https://www.njmutualfund.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
35,Old Bridge Mutual Fund,NaN,https://www.oldbridgemf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
36,PGIM India Mutual Fund,NaN,https://www.pgimindiamf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
37,PPFAS Mutual Fund,NaN,https://amc.ppfas.com/downloads/,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
38,Quant Mutual Fund,NaN,https://quantmutual.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
39,Quantum Mutual Fund,NaN,https://www.quantumamc.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
40,Samco Mutual Fund,NaN,https://www.samcomf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
41,SBI Mutual Fund,NaN,https://www.sbimf.com/forms-and-downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
42,Shriram Mutual Fund,NaN,https://www.shriramamc.in/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
43,Sundaram Mutual Fund,NaN,https://www.sundarammutual.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
44,Tata Mutual Fund,NaN,https://www.tatamutualfund.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
45,Taurus Mutual Fund,NaN,https://www.taurusmutualfund.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
46,The Wealth Company Mutual Fund,NaN,https://www.wealthcompany.in/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
47,TRUST Mutual Fund,NaN,https://www.trustmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
48,Unifi Mutual Fund,NaN,https://www.unifimf.com/,primary_provider,provider_homepage,"[manual_curated, existing_config]",[]
49,Union Mutual Fund,NaN,https://www.unionmf.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
50,UTI Mutual Fund,NaN,https://www.utimf.com/forms-and-downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
51,WhiteOak Capital Mutual Fund,NaN,https://mf.whiteoakamc.com/downloads,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
52,Zerodha Mutual Fund,NaN,https://www.zerodhafundhouse.com/resources/,primary_provider,provider_download_page,"[manual_curated, existing_config]",[]
53,NaN,AMFI,https://www.amfiindia.com/,reference_index,industry_reference_portal,[manual_reference],[]
54,NaN,SEBI,https://www.sebi.gov.in/,reference_index,regulatory_reference_portal,[manual_reference],[]

## 4. Optional small Phase 1A run

In [35]:
RUN_LIVE_SAMPLE = True
SAMPLE_LIMIT = 3

if RUN_LIVE_SAMPLE:
    command = [sys.executable, '-m', 'mutual_fund_ingestion', 'bootstrap-sources', '--dry-run', '--limit', str(SAMPLE_LIMIT)]
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, check=False)
    print(result.stdout)
    if result.stderr:
        print(result.stderr)
else:
    print('Live Phase 1A sample disabled. Set RUN_LIVE_SAMPLE = True to run bootstrap-sources --dry-run.')

{
  "metrics": {
    "total_sources": 55,
    "primary_provider_sources": 53,
    "reference_sources": 2,
    "amfi_reference_sources": 1,
    "sebi_reference_sources": 1,
    "manual_curated_sources": 53,
    "duplicate_merged_sources": 55,
    "sources_missing_seed_urls": 0,
    "sources_requiring_manual_completion": 0
  },
  "warnings": [
    "SEBI reference response is binary and unsupported for deterministic Phase 1A extraction."
  ],
  "sources": [
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.360.one/asset/mutual-funds/downloads/",
      "amc_name": "360 ONE Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://www.abakkusmf.com/statutory-disclosures.html",
      "amc_name": "Abakkus Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://mutualfund.adityabirlacapital.com/forms-and-downloads/portfolio",
      "amc_name": "Aditya Birla Sun Life Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://alphagrepmf.com/",
      "amc_name": "AlphaGrep Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://www.angelonemf.com/",
      "amc_name": "Angel One Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://www.askfinancials.com/",
      "amc_name": "ASK Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://www.axismf.com/statutory-disclosures",
      "amc_name": "Axis Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.bajajamc.com/downloads?statutory-disclosures=",
      "amc_name": "Bajaj Finserv Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://bandhanmutual.com/downloads/disclosures",
      "amc_name": "Bandhan Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.boimf.in/regulatory-reports",
      "amc_name": "Bank of India Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.barodabnpparibasmf.in/downloads/midmonth-portfolio-scheme",
      "amc_name": "Baroda BNP Paribas Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.canararobeco.com/documents/statutory-disclosures/fortnightly-portfolio-disclosure-debt/",
      "amc_name": "Canara Robeco Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://capitalmindmf.com/statutory-disclosures.html#",
      "amc_name": "Capitalmind Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://choicemf.com/",
      "amc_name": "Choice Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://www.dspim.com/mandatory-disclosures/portfolio-disclosures",
      "amc_name": "DSP Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.edelweissmf.com/statutory#Portfolio-of-Schemes",
      "amc_name": "Edelweiss Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://www.franklintempletonindia.com/investor/reports?firstFilter-10",
      "amc_name": "Franklin Templeton Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://growwmf.in/statutory-disclosure/portfolio",
      "amc_name": "Groww Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_disclosure_page",
      "seed_url": "https://www.hdfcfund.com/statutory-disclosure/portfolio/fortnightly-portfolio",
      "amc_name": "HDFC Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.heliosmf.in/portfolio-disclosure/",
      "amc_name": "Helios Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.assetmanagement.hsbc.co.in/en/mutual-funds/investor-resources/information-library#&accordion1446811090=9",
      "amc_name": "HSBC Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.icicipruamc.com/media-center/downloads?currentTabFilter=OtherSchemeDisclosures&&subCatTabFilter=FortnightlyPortfolioDisclosures",
      "amc_name": "ICICI Prudential Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "http://www.ilfsinfrafund.com/other.php",
      "amc_name": "IL&FS Mutual Fund (IDF)",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "statutory_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback for IDF member; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.invescomutualfund.com/literature-and-form?tab=Fortnightly",
      "amc_name": "Invesco Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.itiamc.com/statuory-disclosure",
      "amc_name": "ITI Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_homepage",
      "seed_url": "https://www.jioblackrockamc.com/statutory-disclosure/disclosures/fortnightly-portfolio-disclosure",
      "amc_name": "JioBlackRock Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": "Homepage fallback; refine from profile evidence."
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.jmfinancialmf.com/downloads/Portfolio-Disclosure",
      "amc_name": "JM Financial Mutual Fund",
      "source_name": null,
      "amc_website": null,
      "expected_document_types": [
        "factsheet",
        "portfolio_disclosure"
      ],
      "discovered_from": [
        "manual_curated",
        "existing_config"
      ],
      "confidence": "unknown",
      "priority": "primary",
      "manual_overrides": [
        "seed_url",
        "source_type"
      ],
      "unresolved_reasons": [],
      "access_notes": "",
      "notes": ""
    },
    {
      "enabled": true,
      "source_role": "primary_provider",
      "source_type": "provider_download_page",
      "seed_url": "https://www.kotakmf.com/Information/forms-and-downloads",
      "amc_name": "Kotak Mahindra Mutual Fund",

## 5. Provenance and source summaries

In [36]:
summary_frames = {}
for column in ['discovered_from', 'source_role', 'source_type', 'priority', 'enabled']:
    if column not in registry_df.columns:
        continue
    if column == 'discovered_from':
        values = registry_df[column].explode()
    else:
        values = registry_df[column]
    summary_frames[column] = values.fillna('<missing>').value_counts(dropna=False).rename_axis(column).reset_index(name='count')
    display(summary_frames[column])

metrics = calculate_source_registry_metrics(registry_entries) if registry_entries else {}
pd.DataFrame([{'metric': key, 'value': value} for key, value in metrics.items()])

    discovered_from  count
0    manual_curated     53
1   existing_config     53
2  manual_reference      2

        source_role  count
0  primary_provider     53
1   reference_index      2

                   source_type  count
0       provider_download_page     35
1            provider_homepage     12
2     provider_disclosure_page      6
3    industry_reference_portal      1
4  regulatory_reference_portal      1

    priority  count
0    primary     53
1  secondary      2

   enabled  count
0     True     55

                                metric  value
0                        total_sources     55
1             primary_provider_sources     53
2                    reference_sources      2
3               amfi_reference_sources      1
4               sebi_reference_sources      1
5               manual_curated_sources     53
6             duplicate_merged_sources      0
7            sources_missing_seed_urls      0
8  sources_requiring_manual_completion      0

## 6. Registry quality checks

In [37]:
def normalized_domain(value):
    if not isinstance(value, str) or not value:
        return None
    return urlparse(value).netloc.casefold().removeprefix('www.') or None

quality = {}
if not registry_df.empty:
    quality['missing_amc_name'] = registry_df[registry_df.get('source_role', '').eq('primary_provider') & registry_df.get('amc_name', pd.Series(index=registry_df.index, dtype=object)).isna()]
    quality['missing_seed_url'] = registry_df[registry_df.get('seed_url', pd.Series(index=registry_df.index, dtype=object)).isna()]
    quality['missing_amc_website'] = registry_df[registry_df.get('source_role', '').eq('primary_provider') & registry_df.get('amc_website', pd.Series(index=registry_df.index, dtype=object)).isna()]
    if 'amc_name' in registry_df:
        names = registry_df['amc_name'].astype('string').str.casefold()
        quality['duplicate_amc_names'] = registry_df[names.notna() & names.duplicated(keep=False)]
    if 'seed_url' in registry_df:
        domains = registry_df['seed_url'].map(normalized_domain)
        quality['duplicate_domains'] = registry_df[domains.notna() & domains.duplicated(keep=False)]
    quality['disabled_sources'] = registry_df[~registry_df.get('enabled', True).fillna(False).astype(bool)]
    quality['unknown_source_role'] = registry_df[~registry_df.get('source_role', pd.Series(index=registry_df.index, dtype=object)).isin(['primary_provider', 'reference_index'])]
    if 'source_type' in registry_df:
        quality['unknown_source_type'] = registry_df[registry_df['source_type'].isna() | registry_df['source_type'].eq('unknown')]
    if 'expected_document_types' in registry_df:
        quality['empty_expected_document_types'] = registry_df[~registry_df['expected_document_types'].map(bool)]

quality_counts = pd.DataFrame([{'check': name, 'count': len(frame)} for name, frame in quality.items()])
display(quality_counts)
for name, frame in quality.items():
    if not frame.empty:
        print(f'--- {name} ({len(frame)}) ---')
        display(show_columns(frame, ['amc_name', 'source_name', 'seed_url', 'source_role', 'source_type', 'enabled', 'unresolved_reasons']))

                           check  count
0               missing_amc_name      0
1               missing_seed_url      0
2            missing_amc_website     53
3            duplicate_amc_names      0
4              duplicate_domains      0
5               disabled_sources      0
6            unknown_source_role      0
7            unknown_source_type      0
8  empty_expected_document_types      0

--- missing_amc_website (53) ---

,amc_name,source_name,seed_url,source_role,source_type,enabled,unresolved_reasons
0,360 ONE Mutual Fund,NaN,https://www.360.one/asset/mutual-funds/downloads/,primary_provider,provider_download_page,True,()
1,Abakkus Mutual Fund,NaN,https://www.abakkusmf.com/statutory-disclosure...,primary_provider,provider_homepage,True,()
2,Aditya Birla Sun Life Mutual Fund,NaN,https://mutualfund.adityabirlacapital.com/form...,primary_provider,provider_disclosure_page,True,()
3,AlphaGrep Mutual Fund,NaN,https://alphagrepmf.com/,primary_provider,provider_homepage,True,()
4,Angel One Mutual Fund,NaN,https://www.angelonemf.com/,primary_provider,provider_homepage,True,()
5,ASK Mutual Fund,NaN,https://www.askfinancials.com/,primary_provider,provider_homepage,True,()
6,Axis Mutual Fund,NaN,https://www.axismf.com/statutory-disclosures,primary_provider,provider_disclosure_page,True,()
7,Bajaj Finserv Mutual Fund,NaN,https://www.bajajamc.com/downloads?statutory-d...,primary_provider,provider_download_page,True,()
8,Bandhan Mutual Fund,NaN,https://bandhanmutual.com/downloads/disclosures,primary_provider,provider_download_page,True,()
9,Bank of India Mutual Fund,NaN,https://www.boimf.in/regulatory-reports,primary_provider,provider_download_page,True,()
10,Baroda BNP Paribas Mutual Fund,NaN,https://www.barodabnpparibasmf.in/downloads/mi...,primary_provider,provider_download_page,True,()
11,Canara Robeco Mutual Fund,NaN,https://www.canararobeco.com/documents/statuto...,primary_provider,provider_download_page,True,()
12,Capitalmind Mutual Fund,NaN,https://capitalmindmf.com/statutory-disclosure...,primary_provider,provider_homepage,True,()
13,Choice Mutual Fund,NaN,https://choicemf.com/,primary_provider,provider_homepage,True,()
14,DSP Mutual Fund,NaN,https://www.dspim.com/mandatory-disclosures/po...,primary_provider,provider_disclosure_page,True,()
15,Edelweiss Mutual Fund,NaN,https://www.edelweissmf.com/statutory#Portfoli...,primary_provider,provider_download_page,True,()
16,Franklin Templeton Mutual Fund,NaN,https://www.franklintempletonindia.com/investo...,primary_provider,provider_disclosure_page,True,()
17,Groww Mutual Fund,NaN,https://growwmf.in/statutory-disclosure/portfolio,primary_provider,provider_disclosure_page,True,()
18,HDFC Mutual Fund,NaN,https://www.hdfcfund.com/statutory-disclosure/...,primary_provider,provider_disclosure_page,True,()
19,Helios Mutual Fund,NaN,https://www.heliosmf.in/portfolio-disclosure/,primary_provider,provider_download_page,True,()
20,HSBC Mutual Fund,NaN,https://www.assetmanagement.hsbc.co.in/en/mutu...,primary_provider,provider_download_page,True,()
21,ICICI Prudential Mutual Fund,NaN,https://www.icicipruamc.com/media-center/downl...,primary_provider,provider_download_page,True,()
22,IL&FS Mutual Fund (IDF),NaN,http://www.ilfsinfrafund.com/other.php,primary_provider,provider_homepage,True,()
23,Invesco Mutual Fund,NaN,https://www.invescomutualfund.com/literature-a...,primary_provider,provider_download_page,True,()
24,ITI Mutual Fund,NaN,https://www.itiamc.com/statuory-disclosure,primary_provider,provider_download_page,True,()
25,JioBlackRock Mutual Fund,NaN,https://www.jioblackrockamc.com/statutory-disc...,primary_provider,provider_homepage,True,()
26,JM Financial Mutual Fund,NaN,https://www.jmfinancialmf.com/downloads/Portfo...,primary_provider,provider_download_page,True,()
27,Kotak Mahindra Mutual Fund,NaN,https://www.kotakmf.com/Information/forms-and-...,primary_provider,provider_download_page,True,()
28,LIC Mutual Fund,NaN,https://www.licmf.com/downloads/monthly-portfolio,primary_provider,provider_download_page,True,()
29,Mahindra Manulife Mutual Fund,NaN,https://www.mahindramanulife.com/downloads#MAN...,primary_provider,provider_download_page,True,()
30,Mirae Asset Mutual Fund,NaN,https://www.miraeassetmf.co.in/downloads/portf...,primary_provider,provider_download_page,True,()
31,Motilal Oswal Mutual Fund,NaN,https://www.motilaloswalmf.com/downloads/schem...,primary_provider,provider_download_page,True,()
32,Navi Mutual Fund,NaN,https://navi.com/mutual-fund/downloads/portfolio,primary_provider,provider_homepage,True,()
33,Nippon India Mutual Fund,NaN,https://mf.nipponindiaim.com/investor-service/...,primary_provider,provider_download_page,True,()
34,NJ Mutual Fund,NaN,https://downloads.njmutualfund.com/njmf_downlo...,primary_provider,provider_download_page,True,()
35,Old Bridge Mutual Fund,NaN,https://www.oldbridgemf.com/,primary_provider,provider_homepage,True,()
36,PGIM India Mutual Fund,NaN,https://www.pgimindia.com/mutual-funds/disclos...,primary_provider,provider_download_page,True,()
37,PPFAS Mutual Fund,NaN,https://amc.ppfas.com/downloads/portfolio-disc...,primary_provider,provider_download_page,True,()
38,Quant Mutual Fund,NaN,https://quantmutual.com/statutory-disclosures,primary_provider,provider_download_page,True,()
39,Quantum Mutual Fund,NaN,https://www.quantumamc.com/portfolio/combined/...,primary_provider,provider_download_page,True,()
40,Samco Mutual Fund,NaN,https://www.samcomf.com/StatutoryDisclosure,primary_provider,provider_download_page,True,()
41,SBI Mutual Fund,NaN,https://www.sbimf.com/portfolios,primary_provider,provider_download_page,True,()
42,Shriram Mutual Fund,NaN,https://www.shriramamc.in/investor-statutory-d...,primary_provider,provider_download_page,True,()
43,Sundaram Mutual Fund,NaN,https://www.sundarammutual.com/Monthly-Fortnig...,primary_provider,provider_download_page,True,()
44,Tata Mutual Fund,NaN,https://www.tatamutualfund.com/schemes-related,primary_provider,provider_download_page,True,()
45,Taurus Mutual Fund,NaN,https://www.taurusmutualfund.com/downloads,primary_provider,provider_download_page,True,()
46,The Wealth Company Mutual Fund,NaN,https://www.wealthcompanyamc.in/literature-for...,primary_provider,provider_homepage,True,()
47,TRUST Mutual Fund,NaN,https://www.trustmf.com/disclosures?activeTab=...,primary_provider,provider_download_page,True,()
48,Unifi Mutual Fund,NaN,https://unifimf.com/statutorydocuments/#fortni...,primary_provider,provider_homepage,True,()
49,Union Mutual Fund,NaN,https://unionmf.com/about-us/downloads/fortnig...,primary_provider,provider_download_page,True,()
50,UTI Mutual Fund,NaN,https://www.utimf.com/downloads/consolidate-de...,primary_provider,provider_download_page,True,()
51,WhiteOak Capital Mutual Fund,NaN,https://mf.whiteoakamc.com/regulatory-disclosu...,primary_provider,provider_download_page,True,()
52,Zerodha Mutual Fund,NaN,https://www.zerodhafundhouse.com/resources/dis...,primary_provider,provider_download_page,True,()

## 7. AMFI and reference-source inspection

In [38]:
if registry_df.empty:
    reference_df = registry_df
else:
    reference_mask = registry_df.get('source_role', '').eq('reference_index')
    reference_df = registry_df[reference_mask]

display(show_columns(reference_df, ['source_name', 'seed_url', 'source_role', 'source_type', 'priority', 'discovered_from', 'access_notes', 'notes']))

amfi_rows = reference_df[reference_df.get('source_name', pd.Series(index=reference_df.index, dtype=object)).astype('string').str.casefold().eq('amfi')] if not reference_df.empty else reference_df
amfi_valid = not amfi_rows.empty and amfi_rows.get('source_role', pd.Series(dtype=object)).eq('reference_index').all() and amfi_rows.get('priority', pd.Series(dtype=object)).eq('secondary').all()
print({'amfi_reference_configuration_valid': bool(amfi_valid), 'amfi_rows': len(amfi_rows)})
if not amfi_valid:
    print('WARNING: AMFI should be configured as source_role=reference_index and priority=secondary.')

,source_name,seed_url,source_role,source_type,priority,discovered_from,access_notes,notes
53,AMFI,https://www.amfiindia.com/,reference_index,industry_reference_portal,secondary,"(manual_reference,)",May require VPN depending on the execution env...,"Use for source discovery and validation, not a..."
54,SEBI,https://www.sebi.gov.in/,reference_index,regulatory_reference_portal,secondary,"(manual_reference,)",,Corroborative regulatory reference; discovered...

{'amfi_reference_configuration_valid': True, 'amfi_rows': 1}

## 8. Manual override inspection

In [39]:
if registry_df.empty or 'discovered_from' not in registry_df:
    manual_df = pd.DataFrame()
else:
    manual_mask = registry_df['discovered_from'].map(lambda values: bool(set(values or ()) & {'manual_curated', 'existing_config'}))
    manual_df = registry_df[manual_mask]
show_columns(manual_df, ['amc_name', 'seed_url', 'source_type', 'discovered_from', 'manual_overrides', 'notes'])

,amc_name,seed_url,source_type,discovered_from,manual_overrides,notes
0,360 ONE Mutual Fund,https://www.360.one/asset/mutual-funds/downloads/,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
1,Abakkus Mutual Fund,https://www.abakkusmf.com/statutory-disclosure...,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
2,Aditya Birla Sun Life Mutual Fund,https://mutualfund.adityabirlacapital.com/form...,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
3,AlphaGrep Mutual Fund,https://alphagrepmf.com/,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
4,Angel One Mutual Fund,https://www.angelonemf.com/,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
5,ASK Mutual Fund,https://www.askfinancials.com/,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
6,Axis Mutual Fund,https://www.axismf.com/statutory-disclosures,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
7,Bajaj Finserv Mutual Fund,https://www.bajajamc.com/downloads?statutory-d...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
8,Bandhan Mutual Fund,https://bandhanmutual.com/downloads/disclosures,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
9,Bank of India Mutual Fund,https://www.boimf.in/regulatory-reports,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
10,Baroda BNP Paribas Mutual Fund,https://www.barodabnpparibasmf.in/downloads/mi...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
11,Canara Robeco Mutual Fund,https://www.canararobeco.com/documents/statuto...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
12,Capitalmind Mutual Fund,https://capitalmindmf.com/statutory-disclosure...,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
13,Choice Mutual Fund,https://choicemf.com/,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
14,DSP Mutual Fund,https://www.dspim.com/mandatory-disclosures/po...,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
15,Edelweiss Mutual Fund,https://www.edelweissmf.com/statutory#Portfoli...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
16,Franklin Templeton Mutual Fund,https://www.franklintempletonindia.com/investo...,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
17,Groww Mutual Fund,https://growwmf.in/statutory-disclosure/portfolio,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
18,HDFC Mutual Fund,https://www.hdfcfund.com/statutory-disclosure/...,provider_disclosure_page,"(manual_curated, existing_config)","(seed_url, source_type)",
19,Helios Mutual Fund,https://www.heliosmf.in/portfolio-disclosure/,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
20,HSBC Mutual Fund,https://www.assetmanagement.hsbc.co.in/en/mutu...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
21,ICICI Prudential Mutual Fund,https://www.icicipruamc.com/media-center/downl...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
22,IL&FS Mutual Fund (IDF),http://www.ilfsinfrafund.com/other.php,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback for IDF member; refine from ...
23,Invesco Mutual Fund,https://www.invescomutualfund.com/literature-a...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
24,ITI Mutual Fund,https://www.itiamc.com/statuory-disclosure,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
25,JioBlackRock Mutual Fund,https://www.jioblackrockamc.com/statutory-disc...,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
26,JM Financial Mutual Fund,https://www.jmfinancialmf.com/downloads/Portfo...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
27,Kotak Mahindra Mutual Fund,https://www.kotakmf.com/Information/forms-and-...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
28,LIC Mutual Fund,https://www.licmf.com/downloads/monthly-portfolio,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
29,Mahindra Manulife Mutual Fund,https://www.mahindramanulife.com/downloads#MAN...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
30,Mirae Asset Mutual Fund,https://www.miraeassetmf.co.in/downloads/portf...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
31,Motilal Oswal Mutual Fund,https://www.motilaloswalmf.com/downloads/schem...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
32,Navi Mutual Fund,https://navi.com/mutual-fund/downloads/portfolio,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
33,Nippon India Mutual Fund,https://mf.nipponindiaim.com/investor-service/...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
34,NJ Mutual Fund,https://downloads.njmutualfund.com/njmf_downlo...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
35,Old Bridge Mutual Fund,https://www.oldbridgemf.com/,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
36,PGIM India Mutual Fund,https://www.pgimindia.com/mutual-funds/disclos...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
37,PPFAS Mutual Fund,https://amc.ppfas.com/downloads/portfolio-disc...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
38,Quant Mutual Fund,https://quantmutual.com/statutory-disclosures,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
39,Quantum Mutual Fund,https://www.quantumamc.com/portfolio/combined/...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
40,Samco Mutual Fund,https://www.samcomf.com/StatutoryDisclosure,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
41,SBI Mutual Fund,https://www.sbimf.com/portfolios,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
42,Shriram Mutual Fund,https://www.shriramamc.in/investor-statutory-d...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
43,Sundaram Mutual Fund,https://www.sundarammutual.com/Monthly-Fortnig...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
44,Tata Mutual Fund,https://www.tatamutualfund.com/schemes-related,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
45,Taurus Mutual Fund,https://www.taurusmutualfund.com/downloads,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
46,The Wealth Company Mutual Fund,https://www.wealthcompanyamc.in/literature-for...,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
47,TRUST Mutual Fund,https://www.trustmf.com/disclosures?activeTab=...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
48,Unifi Mutual Fund,https://unifimf.com/statutorydocuments/#fortni...,provider_homepage,"(manual_curated, existing_config)","(seed_url, source_type)",Homepage fallback; refine from profile evidence.
49,Union Mutual Fund,https://unionmf.com/about-us/downloads/fortnig...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
50,UTI Mutual Fund,https://www.utimf.com/downloads/consolidate-de...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
51,WhiteOak Capital Mutual Fund,https://mf.whiteoakamc.com/regulatory-disclosu...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",
52,Zerodha Mutual Fund,https://www.zerodhafundhouse.com/resources/dis...,provider_download_page,"(manual_curated, existing_config)","(seed_url, source_type)",

## 9. Output artifacts

In [40]:
artifact_df = pd.DataFrame([{'artifact': name, 'path': str(path), 'exists': path.exists()} for name, path in PATHS.items()])
display(artifact_df)
if SOURCE_PATHS.report_html.exists():
    print(f'Source registry report: {SOURCE_PATHS.report_html}')

,artifact,path,exists
0,registry_config,/Users/vedaangchopra/all_data/complete_technic...,True
1,candidate_history,/Users/vedaangchopra/all_data/complete_technic...,True
2,latest_snapshot,/Users/vedaangchopra/all_data/complete_technic...,True
3,source_registry_report,/Users/vedaangchopra/all_data/complete_technic...,False

## 10. Readiness summary for Phase 1B

In [41]:
if registry_df.empty:
    readiness = {'total_registry_entries': 0, 'phase_1b_can_run': False, 'recommendation': 'Create or restore the source registry before Phase 1B.'}
else:
    enabled = registry_df.get('enabled', True).fillna(False).astype(bool)
    primary = registry_df.get('source_role', '').eq('primary_provider')
    has_seed = registry_df.get('seed_url', pd.Series(index=registry_df.index, dtype=object)).notna()
    unresolved = registry_df.get('unresolved_reasons', pd.Series([() for _ in registry_df.index], index=registry_df.index)).map(bool)
    enabled_primary = enabled & primary
    usable_primary = enabled_primary & has_seed
    missing_primary = enabled_primary & ~has_seed
    readiness = {
        'total_registry_entries': len(registry_df),
        'enabled_primary_provider_entries': int(enabled_primary.sum()),
        'usable_enabled_primary_entries': int(usable_primary.sum()),
        'reference_only_entries': int(registry_df.get('source_role', '').eq('reference_index').sum()),
        'entries_missing_seed_url': int(missing_primary.sum()),
        'entries_needing_manual_completion': int(unresolved.sum()),
        'phase_1b_can_run': bool(usable_primary.any()),
        'recommendation': 'Run bounded Phase 1B profiling.' if usable_primary.any() else 'Fix Phase 1A provider seed URLs before Phase 1B.',
    }
readiness

{'total_registry_entries': 55,
 'enabled_primary_provider_entries': 53,
 'usable_enabled_primary_entries': 53,
 'reference_only_entries': 2,
 'entries_missing_seed_url': 0,
 'entries_needing_manual_completion': 0,
 'phase_1b_can_run': True,
 'recommendation': 'Run bounded Phase 1B profiling.'}